---
- name: Check peco installation
  shell: /usr/local/bin/peco --version | grep {{version}} 
  register: installed
  ignore_errors: true
  changed_when: false

- name: Download
  get_url: 
    url: https://github.com/peco/peco/releases/download/v{{version}}/peco_linux_amd64.tar.gz
    dest: /tmp/peco_linux_amd64.tar.gz
  register: download
  when: 
    - installed.rc != 0

- name: Extract
  unarchive:
    src: /tmp/peco_linux_amd64.tar.gz
    dest: /tmp
    remote_src: true
  when:
    - installed.rc != 0
    - download | success

- name: Install
  become: true
  command: mv /tmp/peco_linux_amd64/peco /usr/local/bin/peco
  when:
    - installed.rc != 0
    - download | success
