---
- name: Check peco installation
  shell: "{{peco_installation_directory}}/peco --version | grep {{peco_version}}"
  register: installed
  ignore_errors: true
  changed_when: false

- name: Install
  become: "{{peco_privilege_escalation}}"
  unarchive:
    remote_src: true
    src: https://github.com/peco/peco/releases/download/v{{peco_version}}/peco_linux_amd64.tar.gz
    dest: "{{peco_installation_directory}}/peco"
    mode: 0755
    owner: root
    group: root
    extra_opts:
      - --strip-components=1
      - peco_linux_amd64/peco
